@startdot
digraph a {
    label = "Graph-3: min-spawning-tree"
    labelloc  =  t
    fontsize  = 25
    fontcolor = blue

    fontname="Helvetica,Arial,sans-serif"
    node [fontname="Helvetica,Arial,sans-serif"]
    edge [fontname="Helvetica,Arial,sans-serif"]
    rankdir=LR;
    node [shape = circle];
    edge[arrowhead="normal"];
    1 -> 7 [label = "4", minlen=3];
    2 -> 3 [label = "4", minlen=3];
    2 -> 6 [label = "5", minlen=4];
    5 -> 2 [label = "8", minlen=5];
    5 -> 4 [label = "2", minlen=1];
    7 -> 5 [label = "3", minlen=2];
}
@enddot
