@startdot
digraph a {
    fontname="Helvetica,Arial,sans-serif"
    node [fontname="Helvetica,Arial,sans-serif"]
    edge [fontname="Helvetica,Arial,sans-serif"]
    rankdir=LR;
    node [shape = circle];
    edge[arrowhead="normal"];
    1 -> 5 [label = "5", minlen=4];
    3 -> 2 [label = "5", minlen=4];
    5 -> 7 [label = "2", minlen=1];
    7 -> 3 [label = "4", minlen=3];
    7 -> 8 [label = "6", minlen=5];
    7 -> 9 [label = "3", minlen=2];
    9 -> 4 [label = "3", minlen=2];
    9 -> 6 [label = "2", minlen=1];
}
@enddot
